server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Handle clean routing for /maps without needing a trailing slash
    location /maps {
        try_files $uri $uri/ /maps/index.html =404;
    }

    # Universal 404 Error Routing
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
